#!/bin/sh /etc/rc.common
# This file is part of the Doodle3D project (http://doodle3d.com).
#
# Copyright (c) 2013, Doodle3D
# This software is licensed under the terms of the GNU GPL v2 or later.
# See file LICENSE.txt or visit http://www.gnu.org/licenses/gpl.html for full license details.

START=99

start() {
	echo 0 > /sys/devices/virtual/gpio/gpio8/value
	sleep 1
	echo 1 > /sys/devices/virtual/gpio/gpio8/value

	/bin/print3d-manager.sh > /dev/null 2> /dev/null &
}

stop() {
	killall print3d-manager.sh
	killall print3d
}
