#!/bin/sh /etc/rc.common
# This file is part of the Doodle3D project (http://doodle3d.com).
#
# Copyright (c) 2013-2014, Doodle3D
# This software is licensed under the terms of the GNU GPL v2 or later.
# See file LICENSE.txt or visit http://www.gnu.org/licenses/gpl.html for full license details.

START=99
LOG_ID=print3d-mgr
P3D_INOTIFYD_PID_FILE=/var/run/inotifyd-print3d.pid

is_running() {
	test -f $P3D_INOTIFYD_PID_FILE && cat $P3D_INOTIFYD_PID_FILE | xargs kill -0 > /dev/null 2>&1
	#return $?
}

start() {
	if is_running; then
		echo "print3d manager already running"
		exit 1
	fi

	logger -t $LOG_ID "Starting inotifyd for print3d devices"

	inotifyd /usr/libexec/print3d-new-device.sh /dev:n > /dev/null 2>&1 &
	echo $! > $P3D_INOTIFYD_PID_FILE


	#Note: power cycling the USB port also causes inotifyd to detect an 'already connected' device
	echo 0 > /sys/devices/virtual/gpio/gpio8/value
	sleep 1
	echo 1 > /sys/devices/virtual/gpio/gpio8/value
}

stop() {
	if ! is_running; then
		echo "print3d manager not running"
		exit 1
	fi

	logger -t $LOG_ID "Stopping inotifyd for print3d devices"

	cat $P3D_INOTIFYD_PID_FILE | xargs kill > /dev/null 2>&1
	if [ $? -eq 0 ]; then rm $P3D_INOTIFYD_PID_FILE; fi

	#Note: this method of stopping print3d should be improved by use of pid files and an exit handler (`trap exit_handler TERM`) to make sure the socket is removed
	killall print3d > /dev/null 2>&1
}
